return {
    'windwp/nvim-ts-autotag',
    opts = {},
    dependencies = 'nvim-treesitter/nvim-treesitter',
    ft = {
        'astro',
        'glimmer',
        'handlebars',
        'html',
        'javascript',
        'javascriptreact',
        'liquid',
        'markdown',
        'php',
        'rescript',
        'svelte',
        'typescriptreact',
        'twig',
        'typescript',
        'vue',
        'xml',
    },
}
